FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    iproute2 \
    iputils-ping \
    net-tools \
    tcpdump \
    curl \
    wget \
    telnet \
    iperf3 \
    netcat \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]

