FROM ubuntu:20.04

# Use a fast mirror
RUN sed -i 's|http://archive.ubuntu.com|http://mirror.math.princeton.edu/pub/ubuntu|' /etc/apt/sources.list

# Install required tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    iproute2 \
    iputils-ping \
    net-tools \
    tcpdump \
    vim \
    iperf3 \
    tsung \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY tsung.xml tsung.xml

# Default command
CMD ["bash"]
